### ISSUE TITLE
Use israeli-bank-scrapers-core in renderer process

### ISSUE THREAD

**Issue by baruchiro** [baruchiro/israeli-bank-scrapers-desktop#70]
After PR #66 will merge, we will have a strange flow to use the `SCRAPERS` from the `israeli-bank-scrapers-core` in the `renderer` process.

From the [comment](https://github.com/baruchiro/israeli-bank-scrapers-desktop/pull/66#discussion_r367597317):

> I don't understand why the `SCRAPERS` from `israeli-bank-scrapers-core` needs to imported in `scrapers.service`, then imported by `background.js`, who is expose them through the `ipc`, and then this `Importers.vue` call them to add them to the `store`, then uses them by `state` and `getters`.

@Arielgordon123 says that there is a conflict with `ws`.

We need to solve this or open a bug in [israeli-bank-scrapers](https://github.com/eshaham/israeli-bank-scrapers)

**Comment by Arielgordon123** [comment]
because the SCRAPERS are static (unless [israeli-bank-scrapers](https://github.com/eshaham/israeli-bank-scrapers) start to support a new bank) 
we can save a static Json file in our project and import straight to the renderer 

I don't think that these bug related straight to [israeli-bank-scrapers](https://github.com/eshaham/israeli-bank-scrapers)

**Comment by baruchiro** [comment]
Closing, the project moved to https://github.com/brafdlog/budget-tracking
